- hosts: terraform-ansible
  tasks:
  - name: Instalando pacotes python3 e virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: true
    become: true
  - name: Instalando dependencias com pip (Django e Django Rest)
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name:
      - django
      - djangorestframework
  - name: Iniciando o projeto
    shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'